language: php

branches:
  only:
    - master

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar config -g github-oauth.github.com "${GITHUB_TOKEN}"
  - php composer.phar install --prefer-source

script:
  - php -d sendmail_path=mock-service/smtp-mock-server.php vendor/bin/phpunit --stop-on-error --stop-on-failure
