language: php

branches:
  only:
    - master

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer config -g github-oauth.github.com "${GITHUB_TOKEN}"
  - composer install

script:
  - php -d sendmail_path=mock-service/smtp-mock-server.php vendor/bin/phpunit --stop-on-error --stop-on-failure
